name: Python Script CI

on:
  schedule:
    - cron: '0 5 * * *' 
  push:
    branches:
      - master  # Change 'main' to your default branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose another supported OS if needed
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v2  # This action sets up Python
      with:
        python-version: 3.11  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script
      run: python main.py
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SEND_ADDRESS: ${{ secrets.SEND_ADDRESS }}
    - name: Configure Git
      run: |
        git config --global user.name 'GitHubActions'
        git config --global user.email 'GitHubActions@gmail.com'

    - name: Push Changes
      run: |
        git remote add target_repo https://github.com/M4NU5/Politician-trades.git
        git push target_repo test
      env:
        GIT_AUTH_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}